name: flag_app
description: A flag quiz app.

publish_to: 'none'

version: 1.2.11+22

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.0
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_swipe_detector: ^2.0.0
  google_mobile_ads: ^6.0.0
  audioplayers: ^6.5.0
  purchases_flutter: ^8.5.0
  animated_widgets: ^1.1.0
  shake: ^3.0.0
  rate_my_app: ^2.3.2
  flutter_email_sender: ^7.0.0
  url_launcher: ^6.3.2
  launch_app_store: ^1.1.4
  share_plus: ^11.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/flags/
    - assets/image/countries/
    - assets/image/coat of arms/
    - assets/json/
    - assets/json/br/
    - assets/json/de/
    - assets/json/dk/
    - assets/json/es/
    - assets/json/fr/
    - assets/json/no/
    - assets/json/pt/
    - assets/json/se/
    - assets/json/us/
    - assets/icon/
    - assets/sound/
