name: flag_app
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  get: ^4.6.5
  shared_preferences: ^2.0.15
  flutter_swipe_detector: ^2.0.0
  google_mobile_ads: ^1.2.0
  soundpool: ^2.3.0
  purchases_flutter: ^4.3.0
  animated_widgets: ^1.1.0
  shake: ^2.1.0
  rate_my_app: ^1.1.3
  flutter_email_sender: ^5.1.0
  url_launcher: ^6.1.6
  launch_review: ^3.0.1
  share_plus: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/flags/
    - assets/image/countries/
    - assets/image/coat of arms/
    - assets/json/
    - assets/json/br/
    - assets/json/de/
    - assets/json/dk/
    - assets/json/es/
    - assets/json/fr/
    - assets/json/no/
    - assets/json/pt/
    - assets/json/se/
    - assets/json/us/
    - assets/icon/
    - assets/sound/
