name: flag_app
description: A flag quiz app.

publish_to: 'none'

version: 1.4.0+24

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  cupertino_icons: ^1.0.9
  flutter_svg: ^2.3.0
  get: ^4.7.3
  shared_preferences: ^2.5.5
  flutter_swipe_detector: ^2.0.0
  google_mobile_ads: ^8.0.0
  audioplayers: ^6.7.0
  purchases_flutter: ^10.2.0
  animated_widgets: ^1.1.0
  shake: ^3.0.0
  rate_my_app: ^2.4.0
  flutter_email_sender: ^9.0.0
  url_launcher: ^6.3.2
  launch_app_store: ^1.1.4
  share_plus: ^13.1.0
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.2
  confetti: ^0.8.0
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/flags/
    - assets/image/countries/
    - assets/image/coat of arms/
    - assets/json/
    - assets/json/br/
    - assets/json/de/
    - assets/json/dk/
    - assets/json/es/
    - assets/json/fr/
    - assets/json/no/
    - assets/json/pt/
    - assets/json/se/
    - assets/json/us/
    - assets/icon/
    - assets/sound/
